### ISSUE TITLE
Deprecate this repo and replace its usage in pelias

### ISSUE THREAD

**Issue by orangejulius** [pelias/mergeable#5]
This repository hasn't been touched in a while and (as far as I can tell) doesn't do anything [Lodash merge](https://lodash.com/docs/4.17.4#merge), for example, couldn't.

It's currently used in https://github.com/pelias/schema/ and https://github.com/pelias/config/

**Comment by Echelon9** [comment]
Done for schema as of https://github.com/pelias/schema/pull/266

**Comment by orangejulius** [comment]
All done after https://github.com/pelias/config/pull/89!
